### ISSUE TITLE
What does activate function do?

### ISSUE THREAD

**Issue by parthraghav** [cazala/synaptic#103]
Does activate function initialise the neural network? If yes, Neural Networks initialise randomly?

**Comment by bddatest** [comment]
Hello, @parthraghav 

"activation" is like "evaluation" or "using the network".

Normal code flow is like: 
(1) Initialize the network --> (2) Train the network --> (3) Activate the network

```
var perceptron = new Architect.Perceptron(2,3,1);
perceptron.trainer.XOR(); 
result = perceptron.activate([0,1])[0];  //find the result of XOR if the inputs are [0,1]
```

Neural Networks are generally initialized randomly.
That's why you may obtain slightly different results upon different time of training.

Hope this helps :)
