### ISSUE TITLE
Domain URL has expired

### ISSUE THREAD

**Issue by matthamil** [cazala/synaptic#141]
http://synaptic.juancazala.com/ redirects to an expired URL.

**Comment by itbrandonsilva** [comment]
For anyone needing to refer to anything on the site, you can always `git checkout gh-pages`.

**Comment by ivanhuay** [comment]
:sob:

**Comment by cazala** [comment]
Hey, sorry for this guys.. I'm not in Argentina now and my crappy argentine DNS provider can't accept my payments from outside the country for some reason.. I've been dealing with their support people without success, so as I'm not going back till early October, I decided for now just to use a different domain for my personal website, and since synaptic is hanging from that domain, now you can find it here -> [caza.la/synaptic](http://caza.la/synaptic) sorry for the inconvenience.

**Comment by Committing** [comment]
I know some people in Argentina. Want me to hook you up? (Not in the romantic sense)

**Comment by Pickachu** [comment]
taking advantage of the opened issue

It seems that the url (http://juancazala.com/wiki) on this link https://github.com/cazala/synaptic/blob/gh-pages/views/wikipedia.html#L15

is also missing, i could't find the demo on gh-pages either. 

help would be appreciated =D.

**Comment by itbrandonsilva** [comment]
If you mean you can't find the source of the demos, you can find them [here](https://github.com/cazala/synaptic/tree/gh-pages/scripts/controllers).

If you're looking to interact with the demos, I imagine you can just load index.html directly in any browser just fine.

**Comment by matthamil** [comment]
I think he means that the Wikipedia demo in particular is missing. The controller for the demo is pretty bare: https://github.com/cazala/synaptic/blob/gh-pages/scripts/controllers/wikipedia.js

**Comment by itbrandonsilva** [comment]
Ah, my mistake.

**Comment by cazala** [comment]
the old domain is up again, redirecting to the new one
