### ISSUE TITLE
Figuring out if applicable to a scenario

### ISSUE THREAD

**Issue by Dids** [cazala/synaptic#161]
I have an app that tries it's best to calculate release times for a software.
This software releases a new build every Thursday (UTC), at a varying hour/minute.

Currently, I've accumulated a lot of sample data over the past few months, but my estimates are still not as good as I'd like them to be.
I also think that depending on the week of the month, the release times have a larger variance, but not sure as I'm not testing for that.

Anyway, I've recently been looking at neural networks, to see if they could be used for more accurately estimating times (hour & minute), based on previous data.

I've tried to wrap my head around the concepts, but got stuck when trying to figure out what I should be feeding to the inputs, since I'd ideally need to analyze three different things (hour, minute and week of month).

If anyone feels like neural networks might not be the best solution to my problem, feel free to tell me too. :)

**Comment by Jabher** [comment]
I would personally recommend you to look at gradient boosting instead of this, but it can be more complex, so if you'd like to use JS, you should probably process your raw data.
You need a score (how good it's going), day of week, month, season, is this day holiday or weekend, and time itself (without separating it into separate minutes or hours).

Thing is you need to decide which is an actual feature, as NN do not know that people are chilling on holidays, working from 9 to 5, or having a vacation in summer, but it can discover dependencies in it if you will provide characteristics for it

**Comment by Dids** [comment]
Thanks, your answer was thorough enough to get me on the right path. :)
