### ISSUE TITLE
Big training set

### ISSUE THREAD

**Issue by Neoflash1979** [cazala/synaptic#178]
Is the following the only possible format to build a training set? I have a training set of 1000s of entries. What would be the best way to get it properly formatted?

    var trainingSet = [
      {
        input: [0,0],
        output: [0]
      },
      {
        input: [0,1],
        output: [1]
      },
    ]

**Comment by cazala** [comment]
Yes that's the only format that the network will understand if you use the `train()` method. If your training set is a CSV or something else you will need to parse it, and convert it to an array of objects with `input` and `output` props (both arrays of numbers). You can have as many entries as you want in this array.

**Comment by Jabher** [comment]
I'm unsure now, but you can try to use TypedArray for data. Also you probably create training set via function, like 
```javascript
function Record(input, output) {
    return {input, output}
}

var trainingSet = data.map((r) => new Record(r.i, r.o))
```

Looks pointless, but it will actually improve performance due to internal classes of V8 (and possibly other JS engines) - if you're creating big object directly, you are creating bunch of hash-tables, if you're using internal classes, V8 will understand that trainingSet is `Array<{input: Array<number>, output: Array<number>}>` and will optimize memory consumption
