### ISSUE TITLE
Noticeably slower demos on gh-pages.

### ISSUE THREAD

**Issue by jzjzjzj** [cazala/synaptic#20]
I presume you have explored options to couple `requestAnimationFrame` with AngularJS. Can you share your conclusion on this matter?

**Comment by cazala** [comment]
@jzjzjzj i don't notice the demos so much slower, I just pushed an update for demos 3 and 4 (image filters & paint an image) because on every iteration a new angular $digest cycle was being triggered (which was unnecessary and slowed down performance) . Do still see them running slow? If so I will make separate static pages and get rid of angular (it's not actually that needed, it was just faster to code it as a SPA using yeoman)

**Comment by jzjzjzj** [comment]
It seems to run faster now. I think it's OK to leave it as is.
