### ISSUE TITLE
Multi-layer network not converging to XOR dataset

### ISSUE THREAD

**Issue by wagenaartje** [cazala/synaptic#224]
I'm using the example from the Trainer wiki:

```js
var myNetwork = new synaptic.Architect.Perceptron(2, 10,10 , 1);
var trainer = new synaptic.Trainer(myNetwork);

var trainingSet = [
  { input: [0,0], output: [0] },
  { input: [0,1], output: [1] },
  { input: [1,0], output: [1] },
  { input: [1,1], output: [0] }
];

trainer.train(trainingSet,{
	rate: .1,
	iterations: 20000,
	error: .005,
        log:1,
	shuffle: true
});
```

But it is NOT converging. When I remove one of the 10 neuron layers, it does work.

[Run it here](https://jsfiddle.net/wagenaartje/gq8cafc4/2/)

**Comment by cazala** [comment]
Deep networks are way more complex than shallow ones, thus take longer to train (although they can create way more complex abstractions as well). You just need to give the network more time, ie (200k iterations instead of 20k):

```js
var myNetwork = new synaptic.Architect.Perceptron(2, 10,10 , 1);
var trainer = new synaptic.Trainer(myNetwork);

var trainingSet = [
  {
    input: [0,0],
    output: [0]
  },
  {
    input: [0,1],
    output: [1]
  },
  {
    input: [1,0],
    output: [1]
  },
  {
    input: [1,1],
    output: [0]
  },
];

trainer.train(trainingSet,{
	rate: .1,
	iterations: 200000,
	error: .005,
        log:1,
	shuffle: true
});
```

You will see it converging around 75-100k:

<img width="380" alt="screen shot 2017-05-22 at 11 06 22 am" src="https://cloud.githubusercontent.com/assets/2781777/26312661/b7fb0e7e-3ede-11e7-8930-6e5169cd2eda.png">

[Run it here](https://jsfiddle.net/5861g5rj/)
