### ISSUE TITLE
Help define activation function.

### ISSUE THREAD

**Issue by NarendraPatwardhan** [cazala/synaptic#249]
Hello,
Can you please guide me towards how to define a custom activation function and use it in Synaptic? Lets say for the sake of simplicity the function is tanh itself with a different name 'TANH_2'. TANH was the best activation function for training a simple XOR net (error: 10^-4, compared with ReLU 10^-3, Logistic 10^-3) etc.
So I am defining the function TANH_2 exact same way as in source code only adding following lines
```
Neuron.squash.TANH_2 = function(x, derivate) {

  if(derivate)

    return 1 - Math.pow(Math.tanh(x), 2);

  return Math.tanh(x);

};
```
Now for all purposes TANH_2 is exactly same as TANH, but I get error of magnitude 10^-3 instead of 10^-4. (I understand that it depends upon random initialization to certain extent but constantly getting this magnitude).
If the process is incorrect, could you guide me towards how to define a custom activation function in this library? For the sake of simplicity "How to define a function TANH_2 which is same as TANH and gives same results?"

**Comment by wagenaartje** [comment]
I think you did not set up your tests right, here is a working JSFiddle that implements your own activation function: https://jsfiddle.net/wagenaartje/1p6q0gw2/2/

And because of the bad (I want to say: shit) network training optimization that is happening (which wouldn't be necessary if the code would be optimized in the first place), you have to put `myNetwork.setOptimize(false)` because it can't optimize activation functions which aren't already in the library.

So if you want it to work optimized, you have to implement it here as well: https://github.com/cazala/synaptic/blob/master/src/neuron.js#L448

**Comment by NarendraPatwardhan** [comment]
Thank you!
You have been such a great help!

**Comment by NarendraPatwardhan** [comment]
My code was almost the same, your version looks lot elegant though! The difference in error magnitudes was due to optimization done for inbuilt tanh.
