### ISSUE TITLE
Save and Load Training Progress

### ISSUE THREAD

**Issue by rob-gordon** [cazala/synaptic#337]
I can't find any mention or example in the docs for saving training progress in order to resume it later.

Is this possible with synaptic?

Thanks!

**Comment by Devlin556** [comment]
@rob-gordon https://github.com/cazala/synaptic/wiki/Networks#tojsonfromjson network has two methods which allow you to store network progress and restore it later.

**Comment by grigandal625** [comment]
I tried to save the trained network to a file, but when I export the network from a file, it is not trained

I'm using the genetic algorithm to train from [this source](https://github.com/ssusnic/Machine-Learning-Flappy-Bird/blob/master/source/genetic.js)

the network is very well trained by this algorithm
But due to the getting training data from the Internet, I want to save the intermediate population to a file in case of a disconnection

Saving:
```
    var pop = [];
    for (var i = 0; i < GA.Population.length; i++) {//  GA = new GeneticAlgorithm(max_units, winners_count)
        pop.push(GA.Population[i].toJSON());
    }
    fs.writeFileSync('./population.json', JSON.stringify(pop));
    console.log("saved");
```
`
I do saving after each training

Exporting:

```
if (fs.existsSync('./population.json')){
    var d = fs.readFileSync('./population.json', 'utf8');
    var pop = JSON.parse(d);
    for (var i = 0; i < pop.length; i++) {
        var unit = synaptic.Network.fromJSON(pop[i]);
        unit.index = i;
        unit.fitness = 0;
        unit.score = 0;
        unit.isWinner = false;
        GA.Population[i] = unit;
        console.log('unit has been read');
    }
}
Score(GA)
```

Exporting is been doing when I start a new training session
But all of exported networks are not trained and gives bad results on activating **even if they were trained on a immutable data**. I activate exported network on that data and get a very bad result, but at the previous session the result is good

what could it be?

Thanks!

P.S. Sorry for my English, I'm a foreigner
