### ISSUE TITLE
Stopping trainer on custom conditions

### ISSUE THREAD

**Issue by mkondel** [cazala/synaptic#35]
Is there a way to manually stop training?  For example, the error gets down to 0.3, but then starts going up again.  I would like to stop and save the network to JSON now, while error is still 0.3.

Another example, using LSM some pools are just better than others for some solution.  I would like to find these 'good fit' pools.  If the error increases during training, then I would like to stop training and try another LSM.

There might be a way to do this by adding a boolean return value in customLog.  Then the 2 places that use customLog, Trainer.train() and Trainer.workerTrain(), can check a new flag in lines 50 and 188, in addition to the 'iterations' and 'error' conditions.  I could utilize this in my code where I get some external stats from the error value, then make decisions based on that:

```javascript
trainer.train(tset,{
  iterations: 100000,
  rate: 0.00005,
  error: 0.1,
  customLog: {
      every: 1000,
      do: function(data) {
          //add new data point
          stats.Push( data.error )
          //custom log message
          console.log(data.iterations, 'e',data.error, 's',stats.Skewness(), 'k',stats.Kurtosis())
          //this checks a custom condition, returns true to end training
          if( stats.SOME_STAT() > SOME_LIMIT ){
            return true
          }
    }
  }
})
```
Thank you for a great project and making it available to others:)
-Max

**Comment by cazala** [comment]
I like the feature, but the name customLog doesn't seem to be that accurate for this more flexible behaviour, what do you think about renaming it to something like `schedule`?

```
trainer.train(set,{
  iterations: 100000,
  rate: 0.00005,
  error: 0.1,
  schedule: {
      every: 1000,
      do: function(data) {
         if (condition)
               return false;
    }
  }
})
```

we can keep customLog for backward compatibility, which would just call `schedule` and console.warn('Deprecated: use schedule instead`) or something like that...

What do you think?... I must admit that I didn't think that functionality thru that much when I added it, it was more of a hack that I did one time to solve something rather than a carefully planned feature..

**Comment by mkondel** [comment]
Updated my fork, so please see if the new code makes sense.

**Comment by cazala** [comment]
awesome (;
