### ISSUE TITLE
Perceptron.activate undefined

### ISSUE THREAD

**Issue by kaaninel** [cazala/synaptic#46]
Uncaught TypeError: Cannot read property '0' of undefined
    at Perceptron.activate (eval at <anonymous> (http://localhost:3000/lib/ext/devsynaptic.js?3afe0daa1afdee8ef340e23bc09b4fb8729e94bc:814:23), <anonymous>:548:13)
    at Object.Instruction.Train (http://localhost:3000/lib/Network.coffee.js?035a6338280de0bee6bb5004828fdea08605c1a6:46:22)
    at <anonymous>:2:5
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)activate @ VM5256:548Instruction.Train @ Network.coffee:26(anonymous function) @ VM5255:2InjectedScript._evaluateOn @ VM5251:895InjectedScript._evaluateAndWrap @ VM5251:828InjectedScript.evaluate @ VM5251:694

var activate = function(input){
F[1] = input[0];
 F[2] = input[1];
 F[3] = input[2];
 F[4] = input[3];
..
error at line starts with var activate 

[0, 0, 1, 1, 0, 0, 1, 1]
VM5260:2 [0, 0, 0, 0, 0, 1, 0, 0]
VM5260:2 [0, 1, 0, 1, 0, 0, 0, 1]
VM5260:2 [0, 1, 0, 1, 1, 1, 1, 0]
VM5260:2 [0, 0, 0, 1, 1, 0, 1, 0]
VM5260:2 [0, 0, 1, 1, 1, 0, 0, 1]
VM5260:2 [0, 1, 1, 0, 0, 0, 1, 0]
VM5260:2 [0, 1, 0, 0, 0, 0, 1, 0]
VM5260:2 [0, 1, 0, 0, 1, 0, 0, 0]
VM5260:2 [0, 0, 0, 1, 1, 1, 1, 1]
VM5260:2 [0, 0, 1, 1, 1, 0, 1, 1]
VM5260:2 [0, 1, 0, 1, 1, 0, 0, 1]
VM5260:2 [0, 0, 0, 0, 0, 1, 0, 0]
VM5260:2 [0, 1, 0, 0, 1, 1, 1, 1]
VM5260:2 [0, 1, 0, 1, 1, 0, 1, 1]
VM5260:2 [0, 0, 1, 1, 0, 0, 0, 0]
VM5260:2 [0, 0, 1, 0, 1, 0, 0, 1]
VM5260:2 [0, 0, 0, 1, 0, 1, 1, 1]
VM5260:2 [0, 0, 1, 0, 0, 1, 0, 1]
VM5260:2 [0, 1, 0, 0, 1, 1, 0, 1]
VM5260:2 [0, 0, 1, 1, 0, 1, 0, 0]
VM5260:2 [0, 0, 1, 0, 1, 1, 1, 1]
VM5260:2 [0, 1, 0, 1, 0, 0, 0, 1]
VM5260:2 [0, 0, 1, 1, 0, 0, 0, 1]
VM5260:2 [0, 0, 0, 0, 1, 1, 1, 0]
VM5260:2 [0, 0, 1, 1, 1, 0, 1, 0]
VM5260:2 [0, 0, 1, 0, 0, 1, 0, 0]
VM5260:2 [0, 0, 0, 0, 1, 0, 0, 0]
VM5260:2 [0, 1, 0, 0, 1, 0, 0, 1]
VM5260:2 [0, 0, 1, 1, 1, 0, 0, 1]
VM5260:2 [0, 1, 0, 0, 0, 0, 0, 1]
VM5260:2 [0, 0, 0, 0, 0, 0, 0, 0]
VM5260:2 [0, 1, 0, 1, 0, 0, 0, 0]
VM5260:2 [0, 0, 0, 1, 0, 0, 1, 1]
VM5260:2 [0, 1, 0, 1, 1, 0, 1, 1]
VM5260:2 [0, 1, 0, 0, 1, 1, 1, 0]
VM5260:2 [0, 0, 1, 1, 0, 0, 0, 0]
VM5260:2 [0, 0, 0, 1, 1, 1, 1, 0]
VM5260:2 [0, 1, 0, 0, 1, 1, 1, 0]
VM5260:2 [0, 0, 0, 0, 1, 1, 1, 1]
VM5260:2 [0, 0, 0, 1, 1, 0, 1, 1]
VM5260:2 [0, 1, 1, 0, 0, 0, 1, 1]
VM5260:2 [0, 0, 1, 0, 1, 0, 1, 1]
VM5260:2 [0, 0, 1, 0, 0, 0, 0, 0]
VM5260:2 [0, 0, 0, 1, 1, 1, 1, 0]
VM5260:2 [0, 1, 0, 0, 0, 0, 0, 0]
VM5260:2 [0, 0, 0, 0, 1, 0, 0, 0]
VM5260:2 [0, 1, 0, 0, 1, 0, 0, 0]
VM5260:2 [0, 0, 0, 1, 0, 1, 1, 1]
VM5260:2 [0, 1, 0, 1, 1, 1, 1, 1]
VM5260:2 [0, 1, 0, 0, 0, 1, 1, 1]

My inputset for training.

By the way awesome project i was started writing in js and when doing some research i found this and deleted code that i was wrote :) only problem is this error

**Comment by cazala** [comment]
it seems that you are passing are not passing any argument to `.activate(input)` that's why you get `Cannot read property '0' of undefined` on the line that reads `F[1] = input[0];`.

Can you provide the code you are using?

**Comment by kaaninel** [comment]
i check every input parameter on debugger and all of them was right. 

 RandomInputSet: (c,max) ->
    for i in [0..c] by 1
      q = Math.random() * max
      @InputSet.push Converter.ToBinary q
 Train: ->
    while @CurrentIteration < @MaxIteration
      q = Math.round Math.random() * @InputSet.length
      @Network.activate @InputSet[q]
      @Network.propagate @LearningRate,@DesiredSet[q]
      @CurrentIteration++
      console.log @CurrentIteration

Example usage :

  @net= new Network "net",8,8,8,8
  @net.RandomInputSet 50,100
  @net.Train();

**Comment by cazala** [comment]
Okay, coffeescript is not my strong suit, but I ll do my best. First of all, this line: `@net= new Network "net",8,8,8,8`.

If that's `synaptic.Network()` then I believe you are providing [wrong parameters to the constructor](https://github.com/cazala/synaptic/blob/master/src/network.js#L9). The `Network` class expects to receive a `layers` object, containing an input and output layer, and an array of hidden layers. If what you are trying to do is a **perceptron** (one input layer with 8 neurons, one output layer with 8 neurons, and 2 hidden layers of 8 neurons each) then you should use the `Architect.Perceptron` class ([see more](https://github.com/cazala/synaptic/wiki/Architect#perceptron))

Second thing, and what I believe is causing the `undefined` input, you are picking inputs from your input set using the following:

```
q = Math.round Math.random() * @InputSet.length
@Network.activate @InputSet[q] 
```

That will eventually return a `q` that's out of the bounds of the inputSet array, since you are using `Math.round`, instead of `Math.floor`. Lets say your input set has 50 inputs, then eventually `Math.round(Math.random() * 50)` will return a value of `50`, that will make `q` be equal to `50` and that will make `inputSet[q]` be equal to `undefined`, and that's what causes the `activate` method to fail with that error.

Simple test:

```
a = 0;
while(Math.round(Math.random() * 50) != 50) a++;
console.log(a);
```

**Comment by kaaninel** [comment]
Wow i have been fighting with this error for 2 days. I wont use replace all again :D 
It wasn't synaptics network parameters seems right now thanks :) If this works it could be huge project and your project is core of it :D

**Comment by cazala** [comment]
I'm glad i could help and that you find the library useful ^^ and I'm looking forward to see what you come up with!

**Comment by kaaninel** [comment]
How we take mse ?
