### ISSUE TITLE
Source code for wikipedia demo

### ISSUE THREAD

**Issue by danielsvane** [cazala/synaptic#83]
Thank you for this amazing project. I've been trying to find the source code for the "Read from Wikipedia" demo. There is a link to https://github.com/cazala/synaptic/tree/gh-pages/scripts, but I can't seem to find what I'm looking for.

**Comment by cazala** [comment]
Hi @danielsvane, you didn't find it because it wasn't in GitHub. I just created a new repo [here](https://github.com/cazala/synaptic-wikipedia) and threw the source in there so you can check it out. It's really old (it was the first demo-thingy I did with this lib), I threw the newest version of synaptic in it, I don't know if it will run with it or not. But at least you can get an idea of how it works. I hope that helps :)

**Comment by danielsvane** [comment]
Thanks @cazala
