### ISSUE TITLE
Different connection values on toJSON data.

### ISSUE THREAD

**Issue by vkaracic** [cazala/synaptic#98]
I'm in the process of creating a simple UI for training neural networks and as it's backend I'm using synapticJS. I've implemented an option to save the trained neural network (using the [ ``toJSON`` ](https://github.com/cazala/synaptic/blob/master/dist/synaptic.js#L877) method) but I see some differences in the connection weights between neurons. I store my network in a global variable and after inspecting it after training I have these values for weights:
```
...
FROM:  0  TO:  2  W:  -0.03486567364710273
FROM:  0  TO:  3  W:  -0.0015188823234542903
...
```
After saving it / running ``toJSON`` I see these values in the JSON file:
```
...
{"from":"0","to":"2","weight":-6.232729048356611,"gater":null},
{"from":"0","to":"3","weight":-5.5046626547512965,"gater":null}
...
```
Looking further into the ``toJSON`` method I see that the network neurons' connection weight is stored which leaves me clueless to the situation. How, where and why does this change from the network object's connection values to the JSON object's connection ones?

**Comment by simplicitylab** [comment]
Had you got any luck with finding a solution ? Have trained a ANN with good results but from the moment I import my exported network it does't seem to work anymore. 

I think it may be because of the same reasons.

**Comment by cazala** [comment]
That's because you are using an optimized network (they are all optimized by default unless you use `myNetwork.setOptimize(false)`). When a network is optimized, it creates a huge array and hardcodes a single function for activation and another one for propagation that use that memory array. If you want to populate back the values from the memory array the properties in the network's neurons, you need to call `myNetwork.restore()`, then you can inspect it and you should see the same values as when you use `toJSON`

**Comment by vkaracic** [comment]
You are correct! Thanks for the answer!

**Comment by cazala** [comment]
Your are welcome (: let me know if you publish this UI for training, I'm looking forward to see something like that!

**Comment by vkaracic** [comment]
Of course! It's currently in (heavily) development: https://github.com/vkaracic/JARVIS
